In [2]:
from Layer import Tensor, Convolution2D, Flatten, Dense, MaxPooling2D
from NetWork import *
import numpy as np
from Activator import *

Input = Tensor(3,3)
x = np.array([1,2,1,2,0,3,4,1,2,1,2,0,3,4,1,2,2,1]).reshape(2,3,3)
convolution2D= Convolution2D(inputShape=(2,3,3), filters=2, kernel=(2, 2), biasUsed=True,activation='x')
convolution2D.weights = np.array([1,-1,0,1,1,-1,2,3,1,-1,0,-1,2,3,1,2]).reshape(2,2,2,2)
print(x)
print(convolution2D.forward(x))
print()
print(convolution2D.weights)
print(convolution2D.bias)
print(convolution2D.feedBackward(np.array([1]*8).reshape(2,2,2)))
print(convolution2D.loss_div_bias)
print(convolution2D.loss_div_weights)

[[[1 2 1]
  [2 0 3]
  [4 1 2]]

 [[1 2 0]
  [3 4 1]
  [2 2 1]]]
[[[15.64109972 16.92013295]
  [12.17045683  9.21487945]]

 [[17.78990621  8.11547989]
  [25.26079432  9.48938204]]]
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]]

[[[[ 1 -1]
   [ 0  1]]

  [[ 1 -1]
   [ 2  3]]]


 [[[ 1 -1]
   [ 0 -1]]

  [[ 2  3]
   [ 1  2]]]]
[[[-0.35890028 -0.07986705]
  [ 0.17045683  0.21487945]]

 [[-0.21009379  0.11547989]
  [ 0.26079432 -0.51061796]]]
0 0 0 0
[[1 1]
 [1 1]]
[[1 2]
 [2 0]]
0 0 0 1
[[1 1]
 [1 1]]
[[2 1]
 [0 3]]
0 0 1 0
[[1 1]
 [1 1]]
[[2 0]
 [4 1]]
0 0 1 1
[[1 1]
 [1 1]]
[[0 3]
 [1 2]]
0 1 0 0
[[1 1]
 [1 1]]
[[1 2]
 [3 4]]
0 1 0 1
[[1 1]
 [1 1]]
[[2 0]
 [4 1]]
0 1 1 0
[[1 1]
 [1 1]]
[[3 4]
 [2 2]]
0 1 1 1
[[1 1]
 [1 1]]
[[4 1]
 [2 1]]
1 0 0 0
[[1 1]
 [1 1]]
[[1 2]
 [2 0]]
1 0 0 1
[[1 1]
 [1 1]]
[[2 1]
 [0 3]]
1 0 1 0
[[1 1]
 [1 1]]
[[2 0]
 [4 1]]
1 0 1 1
[[1 1]
 [1 1]]
[[0 3]
 [1 2]]
1 1 0 0
[[1 1]
 [1 1]]
[[1 2]
 [3 4]]
1 1 0 1
[[1 1]
 [1 1]]
[[2 0